services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Asia/Tokyo
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./data:/data

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "445:445"
    volumes:
      - ./samba/config:/etc/samba:ro
      - ./data:/data
      - ./samba/run:/run/bin:ro
    secrets:
      - source: samba-secrets
        target: /run/secrets
    command: /bin/sh -c "/run/bin/entrypoint.sh"

secrets:
  samba-secrets:
    file: ./samba/secrets